/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

/**
 *
 * @author Juan
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_salir = new javax.swing.JButton();
        jLabel_titulo = new javax.swing.JLabel();
        jButton_play = new javax.swing.JButton();
        jButton_instructions = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_salir.setBackground(new java.awt.Color(245, 245, 220));
        jButton_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 40, -1));

        jLabel_titulo.setFont(new java.awt.Font("Adobe Hebrew", 1, 48)); // NOI18N
        jLabel_titulo.setText("NIM");
        jLabel_titulo.setToolTipText("");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, 50));

        jButton_play.setBackground(new java.awt.Color(245, 245, 220));
        jButton_play.setFont(new java.awt.Font("Adobe Hebrew", 1, 18)); // NOI18N
        jButton_play.setText("Play");
        jButton_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_playMouseClicked(evt);
            }
        });
        jButton_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_playActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jButton_instructions.setBackground(new java.awt.Color(245, 245, 220));
        jButton_instructions.setFont(new java.awt.Font("Adobe Hebrew", 1, 18)); // NOI18N
        jButton_instructions.setText("Instructions");
        jButton_instructions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_instructionsMouseClicked(evt);
            }
        });
        getContentPane().add(jButton_instructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jButton_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_playActionPerformed

    private void jButton_playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_playMouseClicked
        play x = new play();
        x.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton_playMouseClicked

    private void jButton_instructionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_instructionsMouseClicked
       instructions y = new instructions();
       y.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton_instructionsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_instructions;
    private javax.swing.JButton jButton_play;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_wallpaper;
    // End of variables declaration//GEN-END:variables
}
