/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

/**
 *
 * @author Juan
 */
public class modality extends javax.swing.JFrame {

    /**
     * Creates new form play
     */
    public modality() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_salir = new javax.swing.JButton();
        jButton_volver = new javax.swing.JButton();
        jLabel_player = new javax.swing.JLabel();
        jButton_m2 = new javax.swing.JButton();
        jButton_m3 = new javax.swing.JButton();
        jButton_m1 = new javax.swing.JButton();
        jLabel_m1 = new javax.swing.JLabel();
        jLabel_m2 = new javax.swing.JLabel();
        jLabel_m3 = new javax.swing.JLabel();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_salir.setBackground(new java.awt.Color(245, 245, 220));
        jButton_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 40, -1));

        jButton_volver.setBackground(new java.awt.Color(245, 245, 220));
        jButton_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N
        jButton_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_volverMouseClicked(evt);
            }
        });
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        jLabel_player.setBackground(new java.awt.Color(245, 245, 220));
        jLabel_player.setFont(new java.awt.Font("Adobe Hebrew", 1, 48)); // NOI18N
        jLabel_player.setText("Select modality");
        getContentPane().add(jLabel_player, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jButton_m2.setBackground(new java.awt.Color(245, 245, 220));
        jButton_m2.setFont(new java.awt.Font("Adobe Hebrew", 1, 24)); // NOI18N
        jButton_m2.setText("Modality 2");
        jButton_m2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_m2MouseClicked(evt);
            }
        });
        jButton_m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_m2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        jButton_m3.setBackground(new java.awt.Color(245, 245, 220));
        jButton_m3.setFont(new java.awt.Font("Adobe Hebrew", 1, 24)); // NOI18N
        jButton_m3.setText("Modality 3");
        jButton_m3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_m3MouseClicked(evt);
            }
        });
        jButton_m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_m3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        jButton_m1.setBackground(new java.awt.Color(245, 245, 220));
        jButton_m1.setFont(new java.awt.Font("Adobe Hebrew", 1, 24)); // NOI18N
        jButton_m1.setText("Modality 1");
        jButton_m1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_m1MouseClicked(evt);
            }
        });
        jButton_m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_m1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabel_m1.setBackground(new java.awt.Color(245, 245, 220));
        jLabel_m1.setFont(new java.awt.Font("Adobe Hebrew", 0, 18)); // NOI18N
        jLabel_m1.setText("<html>En esta modalidad cualquier jugador puede retirar cualquier cantidad de palillos de una sola fila. Pierde en este caso quien retire el último palillo.<html>");
        getContentPane().add(jLabel_m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1030, 50));

        jLabel_m2.setBackground(new java.awt.Color(245, 245, 220));
        jLabel_m2.setFont(new java.awt.Font("Adobe Hebrew", 0, 18)); // NOI18N
        jLabel_m2.setText("<html>En esta modalidad cualquier jugador puede retirar a lo sumo tres palillos (de cualquier fila). Pierde en este caso quien retire el último palillo.<html>");
        getContentPane().add(jLabel_m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 1040, 50));

        jLabel_m3.setBackground(new java.awt.Color(245, 245, 220));
        jLabel_m3.setFont(new java.awt.Font("Adobe Hebrew", 0, 18)); // NOI18N
        jLabel_m3.setText("<html>En esta modalidad el jugador puede retirar cualquier cantidad de palillos de una sola fila. Gana en este caso quien retire el último palillo.<html>");
        getContentPane().add(jLabel_m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 1050, 50));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jButton_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_volverMouseClicked
        play x = new play();
        x.setVisible(true);
       dispose(); 
    }//GEN-LAST:event_jButton_volverMouseClicked

    private void jButton_m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_m1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_m1ActionPerformed

    private void jButton_m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_m3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_m3ActionPerformed

    private void jButton_m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_m2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_m2ActionPerformed

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void jButton_m1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_m1MouseClicked
        tablerom1j2 x = new tablerom1j2();
        x.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_m1MouseClicked

    private void jButton_m2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_m2MouseClicked
        tablerom2j2 x = new tablerom2j2();
        x.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_m2MouseClicked

    private void jButton_m3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_m3MouseClicked
        tablerom3j2 x = new tablerom3j2();
        x.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_m3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modality().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_m1;
    private javax.swing.JButton jButton_m2;
    private javax.swing.JButton jButton_m3;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel_m1;
    private javax.swing.JLabel jLabel_m2;
    private javax.swing.JLabel jLabel_m3;
    private javax.swing.JLabel jLabel_player;
    private javax.swing.JLabel jLabel_wallpaper;
    // End of variables declaration//GEN-END:variables
}
