/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

/**
 *
 * @author Juan
 */
public class play extends javax.swing.JFrame {

    /**
     * Creates new form play
     */
    public play() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_salir = new javax.swing.JButton();
        jButton_volver = new javax.swing.JButton();
        jLabel_player = new javax.swing.JLabel();
        jButton_player1 = new javax.swing.JButton();
        jButton_player2 = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_salir.setBackground(new java.awt.Color(245, 245, 220));
        jButton_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 40, -1));

        jButton_volver.setBackground(new java.awt.Color(245, 245, 220));
        jButton_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N
        jButton_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_volverMouseClicked(evt);
            }
        });
        getContentPane().add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        jLabel_player.setBackground(new java.awt.Color(245, 245, 220));
        jLabel_player.setFont(new java.awt.Font("Adobe Hebrew", 1, 48)); // NOI18N
        jLabel_player.setText("Select player");
        getContentPane().add(jLabel_player, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jButton_player1.setBackground(new java.awt.Color(245, 245, 220));
        jButton_player1.setFont(new java.awt.Font("Adobe Hebrew", 1, 24)); // NOI18N
        jButton_player1.setText("One player");
        jButton_player1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_player1MouseClicked(evt);
            }
        });
        jButton_player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_player1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        jButton_player2.setBackground(new java.awt.Color(245, 245, 220));
        jButton_player2.setFont(new java.awt.Font("Adobe Hebrew", 1, 24)); // NOI18N
        jButton_player2.setText("Two player");
        jButton_player2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_player2MouseClicked(evt);
            }
        });
        jButton_player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_player2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jButton_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_volverMouseClicked
       inicio x = new inicio();
       x.setVisible(true);
       dispose(); 
    }//GEN-LAST:event_jButton_volverMouseClicked

    private void jButton_player1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_player1MouseClicked
       // modality x = new modality();
       // x.setVisible(true);
       // dispose();
    }//GEN-LAST:event_jButton_player1MouseClicked

    private void jButton_player2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_player2MouseClicked
        modality x = new modality();
        x.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton_player2MouseClicked

    private void jButton_player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_player2ActionPerformed

    private void jButton_player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_player1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_player1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_player1;
    private javax.swing.JButton jButton_player2;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel_player;
    private javax.swing.JLabel jLabel_wallpaper;
    // End of variables declaration//GEN-END:variables
}
